logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.SQL: DEBUG
server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 810130
    url: jdbc:mysql://localhost:3306/my_movie_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
servlet:
  multipart:
    max-file-size: 5MB
    max-request-size: 5MB
    enabled: true
mvc:
  hiddenmethod:
    filter:
      enabled: true
cloudinary:
  cloud-name: dpuujizet
  api-key: 681693292143826
  api-secret: "${CLOUDINARY_SECRET}"